# Generated by Django 3.2 on 2021-05-15 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('remoteworkEval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteworkeval',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 15, 9, 48, 18, 544107, tzinfo=utc)),
        ),
    ]
