# Generated by Django 3.2 on 2021-05-15 10:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remoteworkEval', '0003_auto_20210515_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteworkeval',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 15, 10, 7, 56, 637139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='remoteworkeval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
