# Generated by Django 3.1.4 on 2020-12-14 20:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to=users.models.get_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
