# Generated by Django 3.2 on 2021-05-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210511_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Type de véhicule',
            },
        ),
        migrations.AlterModelOptions(
            name='timewindow',
            options={'verbose_name': 'Fenêtre de temps'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='averageCosumption',
            field=models.IntegerField(blank=True, null=True, verbose_name='Consommation moyenne (l/100km)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='distanceToWork',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance travail domicile (km)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travelDuration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée du trajet (en mn)'),
        ),
    ]
