# Generated by Django 3.2 on 2021-05-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210511_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='agendaRemoteWorking',
            field=models.ManyToManyField(to='users.TimeWindow', verbose_name='Agenda télétravail'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vehicleType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vehicletype', verbose_name='Type de véhicule'),
        ),
    ]
