# Generated by Django 3.2 on 2021-05-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_notation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='averageCosumption',
            field=models.FloatField(blank=True, null=True, verbose_name='Consommation moyenne (l/100km)'),
        ),
    ]
