version: "3"

services:
  agroofdb:
    image: postgres:latest
    expose:
      - ${POSTGRES_PORT:-5432}
    env_file:
      - .env

  api:
    build:
      context: .
    depends_on:
      - db  
    volumes:
      - .:/app
    command: /app/scripts/start_dev_server.sh
    entrypoint: /app/scripts/entrypoint.sh
    restart: on-failure
    ports:
      - ${API_PORT:-80}:8000
    env_file:
      - .env